// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"golodge/common/globalkey"
	"golodge/deploy/script/mysql/genModel"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userHistoryFieldNames          = builder.RawFieldNames(&UserHistory{})
	userHistoryRows                = strings.Join(userHistoryFieldNames, ",")
	userHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(userHistoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userHistoryRowsWithPlaceHolder = strings.Join(stringx.Remove(userHistoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLooklookTravelUserHistoryIdPrefix = "cache:looklookTravel:userHistory:id:"
)

type (
	userHistoryModel interface {
		Insert(ctx context.Context, data *UserHistory) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		FindOne(ctx context.Context, user_id, history_id int64) (*UserHistory, error)
		//FindOneByUserIdAndHistoryId(ctx context.Context, user_id, history_id int64) (*UserHistory, error)
		SelectBuilder() squirrel.SelectBuilder
		FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*UserHistory, error)
		Update(ctx context.Context, data *UserHistory) error
		Delete(ctx context.Context, user_id, history_id int64) error
		DeleteAll(ctx context.Context, user_id int64) error
		DeleteSoft(ctx context.Context, session sqlx.Session, data *UserHistory) error
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserHistory) error
	}

	defaultUserHistoryModel struct {
		sqlc.CachedConn
		table string
	}

	UserHistory struct {
		Id         int64     `db:"id"`
		HistoryId  int64     `db:"history_id"`
		UserId     int64     `db:"user_id"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"`
		DeleteTime time.Time `db:"delete_time"`
	}
)

func newUserHistoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserHistoryModel {
	return &defaultUserHistoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_history`",
	}
}

func (m *defaultUserHistoryModel) Delete(ctx context.Context, user_id, history_id int64) error {
	looklookTravelUserHistoryIdKey := fmt.Sprintf("%s%v%v", cacheLooklookTravelUserHistoryIdPrefix, user_id, history_id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ? and `history_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, user_id, history_id)
	}, looklookTravelUserHistoryIdKey)
	return err
}

func (m *defaultUserHistoryModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *UserHistory) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), " delete err : %+v", err)
	}
	return nil
}

func (m *defaultUserHistoryModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserHistory) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	looklookTravelUserHistoryIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHistoryIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, userHistoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.HistoryId, data.DelState, data.Version, data.DeleteTime, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.HistoryId, data.DelState, data.Version, data.DeleteTime, data.Id, oldVersion)
	}, looklookTravelUserHistoryIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return genModel.ErrNoRowsUpdate
	}
	return nil
}

func (m *defaultUserHistoryModel) DeleteAll(ctx context.Context, user_id int64) error {
	looklookTravelUserHistoryIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHistoryIdPrefix, user_id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, user_id)
	}, looklookTravelUserHistoryIdKey)
	return err
}

func (m *defaultUserHistoryModel) FindOne(ctx context.Context, user_id, history_id int64) (*UserHistory, error) {
	//looklookTravelUserHistoryIdKey := fmt.Sprintf("%s%v%v", cacheLooklookTravelUserHistoryIdPrefix, user_id, history_id)
	var resp UserHistory
	// FindOne里面查询不能带缓存会导致再次添加相同的名宿id可以成功，会出现缓存不一致的问题
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `history_id` = ? limit 1", userHistoryRows, m.table)
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, user_id, history_id)
	//err := m.QueryRowCtx(ctx, &resp, looklookTravelUserHistoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
	//	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `history_id` = ? limit 1", userHistoryRows, m.table)
	//	return conn.QueryRowCtx(ctx, v, query, user_id, history_id)
	//})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserHistoryModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

func (m *defaultUserHistoryModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*UserHistory, error) {

	builder = builder.Columns(userHistoryRows)
	if orderBy == "" {
		// 不知道为啥不能写update_time DESC
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}
	// 生成的SQL和参数
	query, values, err := builder.Where("").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*UserHistory
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
	//looklookTravelUserHomestayIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHomestayIdPrefix, userId)
	//fmt.Println("looklookTravelUserHomestayIdKey",looklookTravelUserHomestayIdKey)
	//var resp []*UserHomestay
	//err := m.QueryRowCtx(ctx, &resp, looklookTravelUserHomestayIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
	//	query := fmt.Sprintf("select %s from %s where `user_id` = ?", userHomestayRows, m.table)
	//	fmt.Println("query:",query)
	//	return conn.QueryRowsCtx(ctx, v, query, userId)
	//})
	//switch err {
	//case nil:
	//	return resp, nil
	//case sqlc.ErrNotFound:
	//	return nil, ErrNotFound
	//default:
	//	return nil, err
	//}
}

func (m *defaultUserHistoryModel) Insert(ctx context.Context, data *UserHistory) (sql.Result, error) {
	data.DelState = globalkey.DelStateNo
	data.DeleteTime = time.Unix(0, 0)
	looklookTravelUserHistoryIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHistoryIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userHistoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.HistoryId, data.UserId, data.DelState, data.Version, data.DeleteTime)
	}, looklookTravelUserHistoryIdKey)
	return ret, err
}

func (m *defaultUserHistoryModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultUserHistoryModel) Update(ctx context.Context, data *UserHistory) error {
	looklookTravelUserHistoryIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHistoryIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userHistoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.HistoryId, data.UserId, data.DelState, data.Version, data.DeleteTime, data.Id)
	}, looklookTravelUserHistoryIdKey)
	return err
}

func (m *defaultUserHistoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLooklookTravelUserHistoryIdPrefix, primary)
}

func (m *defaultUserHistoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userHistoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserHistoryModel) tableName() string {
	return m.table
}
