// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "golodge/app/usercenter/cmd/api/internal/handler/user"
	"golodge/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: user.FileUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/addWishList",
				Handler: user.AddWishListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/browinghistory",
				Handler: user.HistoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/clearHistory",
				Handler: user.ClearHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: user.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/removeHistory",
				Handler: user.RemoveHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/removeWishList",
				Handler: user.RemoveWishListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/updateUserInfo",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/wishList",
				Handler: user.WishListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/wxMiniAuth",
				Handler: user.WxMiniAuthHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
