// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	ws "golodge/app/websocket/cmd/api/internal/handler/ws"
	"golodge/app/websocket/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// chat
				Method:  http.MethodGet,
				Path:    "/chat",
				Handler: ws.ChatHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/websocket/v1"),
	)
}
