// Code generated by goctl. DO NOT EDIT.

package genModel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userHomestayFieldNames          = builder.RawFieldNames(&UserHomestay{})
	userHomestayRows                = strings.Join(userHomestayFieldNames, ",")
	userHomestayRowsExpectAutoSet   = strings.Join(stringx.Remove(userHomestayFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userHomestayRowsWithPlaceHolder = strings.Join(stringx.Remove(userHomestayFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLooklookTravelUserHomestayIdPrefix = "cache:looklookTravel:userHomestay:id:"
)

type (
	userHomestayModel interface {
		Insert(ctx context.Context, data *UserHomestay) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserHomestay, error)
		Update(ctx context.Context, data *UserHomestay) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserHomestayModel struct {
		sqlc.CachedConn
		table string
	}

	UserHomestay struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		HomestayId int64     `db:"homestay_id"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"`
		DeleteTime time.Time `db:"delete_time"`
	}
)

func newUserHomestayModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserHomestayModel {
	return &defaultUserHomestayModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_homestay`",
	}
}

func (m *defaultUserHomestayModel) Delete(ctx context.Context, id int64) error {
	looklookTravelUserHomestayIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHomestayIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, looklookTravelUserHomestayIdKey)
	return err
}

func (m *defaultUserHomestayModel) FindOne(ctx context.Context, id int64) (*UserHomestay, error) {
	looklookTravelUserHomestayIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHomestayIdPrefix, id)
	var resp UserHomestay
	err := m.QueryRowCtx(ctx, &resp, looklookTravelUserHomestayIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userHomestayRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserHomestayModel) Insert(ctx context.Context, data *UserHomestay) (sql.Result, error) {
	looklookTravelUserHomestayIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHomestayIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userHomestayRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.HomestayId, data.DelState, data.Version, data.DeleteTime)
	}, looklookTravelUserHomestayIdKey)
	return ret, err
}

func (m *defaultUserHomestayModel) Update(ctx context.Context, data *UserHomestay) error {
	looklookTravelUserHomestayIdKey := fmt.Sprintf("%s%v", cacheLooklookTravelUserHomestayIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userHomestayRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.HomestayId, data.DelState, data.Version, data.DeleteTime, data.Id)
	}, looklookTravelUserHomestayIdKey)
	return err
}

func (m *defaultUserHomestayModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLooklookTravelUserHomestayIdPrefix, primary)
}

func (m *defaultUserHomestayModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userHomestayRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserHomestayModel) tableName() string {
	return m.table
}
